#查询所有分类
http://localhost:8080/category/findAll
#返回值resultInfo

//添加分类
http://localhost:8080/category/addCategory?cname=分类名

###返回结果:ResultInfo
###会判断分类名是否存在，如果存在则返回false

#更新分类
http://localhost:8080/category/updateCategory?cid=分类id&cname=更新后的分类名
##返回结果ResultInfo
####会根据cid查询分类是否存在，如果不存在则返回false

##删除分类
http://localhost:8080/category/deleteCategory?cid=分类id
##返回结果ResultInfo
####会根据cid查询分类是否存在，如果不存在则返回false