##获取图片验证码
http://localhost:8080/user/checkCode
##返回值：图片

##获取手机验证码
http://localhost:8080/user/getCheckNum?phoneNumber=手机号

####返回值：ResultInfo

####查询username是否重复
http://localhost:8080/user/findByUsername?username=username
##返回值resultInfo


##注册用户
http://localhost:8080/user/register

###必填参数checkCode
###可选参数 User类
##返回值resultInfo

##登录用户
http://localhost:8080/user/login
##参数：checkCode、username、paasword
##返回值：resultInfo

###退出用户
http://localhost:8080/user/exit
##跳转到login.html页面

###使用手机号获取验证码登录
http://localhost:8080/user/phonelogin
###参数验证码 手机号